[package]
name = "near-lite-client"
authors = ["Composable Developers"]
version = "0.1.0"
edition = "2021"
homepage = "https://composable.finance"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = {version = "0.9.3", default-features = false }

[dev-dependencies]
sha2 = "0.10.2"
