package types

import (
	"encoding/json"
	"math/big"

	"github.com/near/borsh-go"
)

type CryptoHash = [32]uint8
type CryptoHashBase58Encoded = string
type Gas = uint64
type Balance = big.Int // borsh maps u128 -> big.Int
type BlockHeight = uint64
type AccountId = string

// for merkle tree
type Direction = borsh.Enum
type DirectionJson = string

const (
	Left Direction = iota
	Right
)

type MerkleHash = CryptoHash
type MerklePathItemJson struct {
	Hash      CryptoHashBase58Encoded `json:"hash"`
	Direction DirectionJson           `json:"direction"`
}

type MerklePathItem struct {
	Hash      MerkleHash
	Direction Direction
}
type MerklePath = []MerklePathItem
type MerklePathJson = []MerklePathItemJson

type ValidatorStakeViewV1 struct {
	AccountId AccountId
	PublicKey PublicKey
	Stake     Balance
}

type ValidatorStakeViewV2 struct {
	AccountId   AccountId
	PublicKey   PublicKey
	Stake       Balance
	IsChunkOnly bool
}

// crypto primitives
type Signature struct {
	Enum    uint8
	ED25519 [64]byte
	// SECP256K1 []byte // TODO: be more specific on the number of bytes
}

type ED25519PublicKey struct {
	Inner CryptoHash
}

type PublicKey struct {
	Enum    borsh.Enum `borsh_enum:"true"`
	ED25519 ED25519PublicKey
	/// 512 bit elliptic curve based public-key used in Bitcoin's public-key cryptography.
	// SECP256K1 Secp256K1PublicKey
}

type ApprovalInner struct {
	Enum        borsh.Enum `borsh_enum:"true"`
	Endorsement Endorsement
}

type Endorsement struct {
	Inner CryptoHash
}

// rpc structs
type ValidatorStakeView struct {
	Enum borsh.Enum `borsh_enum:"true"`
	V1   ValidatorStakeViewV1
	V2   ValidatorStakeViewV2
}

type BlockHeaderInnerLiteViewJson struct {
	Height        BlockHeight             `json:"height"`
	EpochId       CryptoHashBase58Encoded `json:"epoch_id"`
	NextEpochId   CryptoHashBase58Encoded `json:"next_epoch_id"`
	PrevStateRoot CryptoHashBase58Encoded `json:"prev_state_root"`
	OutcomeRoot   CryptoHashBase58Encoded `json:"outcome_root"`
	/// Legacy json number. Should not be used.
	Timestamp        uint64                  `json:"timestamp"`
	TimestampNanosec string                  `json:"timestamp_nanosec"`
	NextBpHash       CryptoHashBase58Encoded `json:"next_bp_hash"`
	BlockMerkleRoot  CryptoHashBase58Encoded `json:"block_merkle_root"`
}

type BlockHeaderInnerLiteView struct {
	Height        BlockHeight
	EpochId       CryptoHash
	NextEpochId   CryptoHash
	PrevStateRoot CryptoHash
	OutcomeRoot   CryptoHash
	/// Legacy json number. Should not be used.
	Timestamp       uint64
	NextBpHash      CryptoHash
	BlockMerkleRoot CryptoHash
}

type LightClientBlockViewJson struct {
	PrevBlockHash      CryptoHashBase58Encoded      `json:"prev_block_hash"`
	NextBlockInnerHash CryptoHashBase58Encoded      `json:"next_block_inner_hash"`
	InnerLite          BlockHeaderInnerLiteViewJson `json:"inner_lite"`
	InnerRestHash      CryptoHashBase58Encoded      `json:"inner_rest_hash"`
	NextBps            []json.RawMessage            `json:"next_bps"`
	ApprovalsAfterNext []*json.RawMessage           `json:"approvals_after_next"`
}

type LightClientBlockView struct {
	PrevBlockHash      CryptoHash
	NextBlockInnerHash CryptoHash
	InnerLite          BlockHeaderInnerLiteView
	InnerRestHash      CryptoHash
	NextBps            []ValidatorStakeView
	ApprovalsAfterNext []*Signature
}

type LightClientBlockLiteViewJson struct {
	PrevBlockHash CryptoHashBase58Encoded      `json:"prev_block_hash"`
	InnerRestHash CryptoHashBase58Encoded      `json:"inner_rest_hash"`
	InnerLite     BlockHeaderInnerLiteViewJson `json:"inner_lite"`
}

type LightClientBlockLiteView struct {
	PrevBlockHash CryptoHash
	InnerRestHash CryptoHash
	InnerLite     BlockHeaderInnerLiteView
}
type ExecutionOutcomeViewJson struct {
	Logs        []string           `json:"logs"`
	ReceiptIds  []Base58CryptoHash `json:"receipt_ids"`
	GasBurnt    Gas                `json:"gas_burnt"`
	TokensBurnt string             `json:"tokens_burnt"`
	ExecutorId  AccountId          `json:"executor_id"`
	Status      json.RawMessage    `json:"status"`
}
type ExecutionOutcomeView struct {
	/// Logs from this transaction or receipt.
	Logs []string
	/// Receipt IDs generated by this transaction or receipt.
	ReceiptIds []CryptoHash
	/// The amount of the gas burnt by the given transaction or receipt.
	GasBurnt Gas
	/// The amount of tokens burnt corresponding to the burnt gas amount.
	/// This value doesn't always equal to the `gas_burnt` multiplied by the gas price, because
	/// the prepaid gas price might be lower than the actual gas price and it creates a deficit.
	TokensBurnt big.Int
	/// The id of the account on which the execution happens. For transaction this is signer_id,
	/// for receipt this is receiver_id.
	ExecutorId AccountId
	/// Execution status. Contains the result in case of successful execution.
	Status []byte // NOTE(blas): no need to deserialize this one (in order to avoid having to define too many unnecessary struct
}

type ExecutionOutcomeWithIdViewJson struct {
	Proof     []MerklePathItemJson     `json:"proof"`
	BlockHash CryptoHashBase58Encoded  `json:"block_hash"`
	Id        CryptoHashBase58Encoded  `json:"id"`
	Outcome   ExecutionOutcomeViewJson `json:"outcome"`
}

type ExecutionOutcomeWithIdView struct {
	/// Proof of the execution outcome
	Proof MerklePath
	/// Block hash of the block that contains the outcome root
	BlockHash CryptoHash
	/// Id of the execution (transaction or receipt)
	Id CryptoHash
	/// The actual outcome
	Outcome ExecutionOutcomeView
}

type RpcLightClientExecutionProofResponseJson struct {
	OutcomeProof     ExecutionOutcomeWithIdViewJson `json:"outcome_proof"`
	OutcomeRootProof MerklePathJson                 `json:"outcome_root_proof"`
	BlockHeaderLite  LightClientBlockLiteViewJson   `json:"block_header_lite"`
	BlockProof       MerklePathJson                 `json:"block_proof"`
}

type RpcLightClientExecutionProofResponse struct {
	/// Proof of execution outcome
	OutcomeProof ExecutionOutcomeWithIdView
	/// Proof of shard execution outcome root
	OutcomeRootProof MerklePath
	/// A light weight representation of block that contains the outcome root
	BlockHeaderLite LightClientBlockLiteView
	/// Proof of the existence of the block in the block merkle tree,
	/// which consists of blocks up to the light client head
	BlockProof MerklePath
}

// rpc types
type Base58CryptoHash = string

func NewValidatorStakeViewFromV1(v1 ValidatorStakeViewV1) ValidatorStakeView {
	return ValidatorStakeView{
		Enum: 0,
		V1:   v1,
	}
}

func NewValidatorStakeViewFromV2(v2 ValidatorStakeViewV2) ValidatorStakeView {
	return ValidatorStakeView{
		Enum: 1,
		V2:   v2,
	}
}
