[package]
name = "near-merkle-proofs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = {version = "0.9.3", default_features = false }
near-primitives = "0.12.0"
no-std-compat = {version = "0.4.1", features = [ "alloc", "compat_hash" ] }

[dev-dependencies]
sha2 = "0.10.2"
