name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-11-08
          components: rustfmt
          target: wasm32-unknown-unknown
          override: true
          default: true
      - name: Build
        run: cargo build --verbose
      - name: Check near light client
        run: cargo check --no-default-features --target=wasm32-unknown-unknown --manifest-path=./near-lite-client/Cargo.toml
      - name: Run near lite client
        run: cd near-lite-client && cargo test --verbose